---
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  jest: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: module
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: detect
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - prettier
  - simple-import-sort
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  simple-import-sort/imports: error
  simple-import-sort/exports: error